//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kickoff
    {
        public int ID { get; set; }
        public string KickoffNumber { get; set; }
        public System.DateTime KickoffDate { get; set; }
        public int ParentID { get; set; }
        public bool IsReliabilityTest { get; set; }
        public bool IsPPAP { get; set; }
        public bool IsCustomerDocForm { get; set; }
        public bool IsLiteonDocForm { get; set; }
        public bool IsLiteonConFirm { get; set; }
        public bool IsCustomerConFirm { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
