//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFile
    {
        public int ID { get; set; }
        public int RefID { get; set; }
        public int UploadType { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string ContentType { get; set; }
        public int FileSize { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime ModifyDateTime { get; set; }
        public int ModifyUserID { get; set; }
        public bool IsProductSpec { get; set; }
        public bool IsTestInstruction { get; set; }
        public bool IsCustomerBOM { get; set; }
        public bool IsBinResistorTable { get; set; }
        public bool IsPCBA { get; set; }
        public bool IsPCB { get; set; }
        public bool IsHarness { get; set; }
        public bool IsGerber { get; set; }
        public bool IsCoordinate { get; set; }
        public bool IsSchematics { get; set; }
        public bool IsComp { get; set; }
        public bool IsPVTestPlan { get; set; }
        public bool IsSVRF { get; set; }
    }
}
