//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDRInformation
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public bool IsElectronic { get; set; }
        public bool IsSoftware { get; set; }
        public bool IsMechanism { get; set; }
        public bool IsOptic { get; set; }
        public bool IsRF { get; set; }
        public bool IsLAK { get; set; }
        public bool IsLAW { get; set; }
        public bool IsLGA { get; set; }
        public bool IsLAT { get; set; }
        public bool IsTCH { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TxtOther_1 { get; set; }
        public bool IsSpec { get; set; }
        public bool IsGERBER { get; set; }
        public bool IsWireDwg { get; set; }
        public bool IsSample { get; set; }
        public bool IsBOM { get; set; }
        public bool IsAssemblyDwg { get; set; }
        public bool IsDChart { get; set; }
        public bool IsCKT { get; set; }
        public bool Is2D { get; set; }
        public bool Is3D { get; set; }
        public bool IsROHS { get; set; }
        public bool IsELV { get; set; }
        public bool IsVLS { get; set; }
        public string TxtOthers_2 { get; set; }
        public bool IsMaterialCost { get; set; }
        public bool IsPackageCost { get; set; }
        public bool IsProcessCost { get; set; }
        public bool IsProductHourCost { get; set; }
        public bool IsTestHourCost { get; set; }
        public bool IsSamplePrice { get; set; }
        public bool IsModuleFee { get; set; }
        public bool IsSampleFee { get; set; }
        public bool IsHandMoldingFee { get; set; }
        public bool IsTravelFee { get; set; }
        public bool IsTestFee { get; set; }
        public bool IsDevelopFee { get; set; }
        public bool IsVerifyToolFee { get; set; }
        public string TxtOthers_3 { get; set; }
        public bool IsAssignForm { get; set; }
        public bool IsProposal { get; set; }
        public bool IsDevPlan { get; set; }
        public bool IsStepPrice { get; set; }
        public string TxtOthers_4 { get; set; }
        public bool IsNewProductDev { get; set; }
        public bool IsODM { get; set; }
        public bool IsExtension { get; set; }
        public bool IsSoftwareDev { get; set; }
        public bool IsSoftwareParam { get; set; }
        public bool IsInnerTechDev { get; set; }
        public bool IsOEM { get; set; }
        public bool IsProductionTrans { get; set; }
        public bool IsDelete { get; set; }
    }
}
